(#7) Adicionando as ferramentas utilizadas
Interacao-Humano-Computador/2020.2-Ingresso.eear pull request #10
Opened 2021-03-02 19:08 UTC by yandrade1305

## Descrição

Adição de ferramentas utilizadas

## Tarefas Realizadas

- Levantar e listar as ferramentas que serão utilizadas;
- Criar uma pasta compartilhada no Google Drive;
- Criar o slide para apresentação;

## Issues Relacionadas

#7

2021-03-03 01:40 UTC, DanielPortods requested changes

2021-03-03 01:40 UTC, DanielPortods commented on docs/planejamento.md
> +![Alt text](./assets/imagens/Teams.png) | Microsoft Teams | Plataforma usada para reunião e para gravação das apresentações do projeto.
Para reuniões estamos usando o Discord e para apresentações será o StreamYard...

2021-03-03 12:00 UTC, yandrade1305 commented on docs/planejamento.md
> +![Alt text](./assets/imagens/Teams.png) | Microsoft Teams | Plataforma usada para reunião e para gravação das apresentações do projeto.
Feito!

2021-03-03 23:18 UTC, DanielPortods approved these changes

2021-03-05 01:35 UTC, Bruno-Felix approved these changes
Boa!!

2021-03-05 01:35 UTC, merged