32 storyboard
Interacao-Humano-Computador/2020.2-Ingresso.eear pull request #35
Opened 2021-04-09 05:35 UTC by DenysRogeres

## Descrição

## Tarefas Realizadas
Adição da página Storyboard

## Issues Relacionadas
#32

2021-04-09 11:41 UTC, DanielPortods requested changes
Coloquem as legendas e alguma forma de acessar a imagem num tamanho maior.

2021-04-09 11:41 UTC, DanielPortods commented on docs/design-ava-dese/nivel-1/storyboard.md
> +
Colocar uma legenda e alguma forma de acessar a imagem num tamanho maior.

2021-04-09 11:44 UTC, DanielPortods requested changes
Coloquem um link no nome das personas que redirecione para a mesma no documento de personas.

2021-04-09 13:05 UTC, DanielPortods approved these changes
🏆

2021-04-11 23:52 UTC, Bruno-Felix approved these changes
Nice!!

2021-04-11 23:53 UTC, merged